### PR TITLE
 Extension of the shop subpage [WDP210701 37]

### PR DESCRIPTION
**Pull request by AniaSzwal**
PROBLEM: Currently the shop subpage exists but is empty.
Before starting work on the shop subpage, I had to prepare an initial outline of the containers in which the future elements will be located

the shop page must include:
- container with a width of 100% with the inscription Banner
- container divided into 2 parts, the first (from the left) with the text (Product List) is to be 9/12 wide, the second with the words Filters 3/12 wide
- the last container labeled Brands. 100% width.

SOLUTION: I did whole template

### CODE REVIEW

**Comment by B7atis** [comment]
Strona shop działa i ma prawidłowe parametry według wytycznych z zadania. Niestety po wprowadzeniu zmian w pliku FeatureBoxes.js przestało działać RWD z zdania: WDP210701-16. Sprawdź to proszę i przywróć tą funkcjonalność. Poza tym są widoczne konflikty. :)

**Comment by AniaSzwal** [comment]
Should be ok now

**Comment by B7atis** [comment]
Yeah. It is okay. I accept.

**Review by B7atis — APPROVED** [review]
Accepted.

**Pull request merged**
